# Generated by Django 6.0.4 on 2026-06-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
